Gemini.Net/Models/ErrorViewModel.cs
namespace Gemini.Net.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Gemini.Net/Models/GeminiPrompt.cs
namespace Gemini.Net.Models
{

    public class GeminiPrompt
    {
        public GeminiPrompt(int id, string prompt)
        {
            Id = id;
            Prompt = prompt;
        }
        public GeminiPrompt()
        {
             
        }

        public int? Id { get; set; }


        public string Prompt { get; set; }
        public string? Response { get; set; }
    }

}

Gemini.Net/Controllers/GeminiController.cs
using Gemini.Net.Models;
using GeminiCSharp;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

namespace Gemini.Net.Controllers
{
    public class GeminiController : Controller
    {
        private readonly IConfiguration _configuration;
        public GeminiController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        // GET: GeminiController
        public IActionResult Index(GeminiPrompt prompt)
        {
            var menu = "Faça sua pergunta para o Gemini: ";
            ViewBag.Menu = menu;
            return View(prompt); 
        }

         
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostPrompt([Bind("Id,Prompt")]GeminiPrompt form)
        {
            try
            {
                var apiKey = _configuration.GetValue<string>("API_KEY");
                var geminiChat = new GeminiChat(apiKey);

                 
               
                using var httpClient = new HttpClient();


                var response = await geminiChat.SendMessageAsync(form.Prompt, httpClient);
                if (response is not null)
                {
                    form.Response = response;
                    return View("Index",form);
                }
                Console.WriteLine($"[Gemini]: {form}");
                geminiChat.ResetToNewChat();
                return View("Index");
            }
            catch
            {
                return View("Index");
            }
        }

         
    }
}

Gemini.Net/Controllers/HomeController.cs
using Gemini.Net.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gemini.Net.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gemini.Net/Views/Gemini/Index.cshtml
@model Gemini.Net.Models.GeminiPrompt

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4>GeminiPrompt</h4>

<h6>@ViewBag.Menu</h6>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="PostPrompt">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prompt" class="control-label"></label>
                <input asp-for="Prompt" class="form-control" />
                <span asp-validation-for="Prompt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
       
    </div>
</div>
@if(Model.Prompt is not null)
{
    <div class="justify-content-center align-content-center">
        <p class=" fw-bold">Resposta</p>
        <p>@Html.DisplayFor(model => model.Response)</p>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gemini.Net/Views/Home/Index.cshtml
@model Gemini.Net.Models.GeminiPrompt

@{
    ViewData["Title"] = "EnviaPromptPageAsync";
}

<h1>EnviaPromptPageAsync</h1>

<div>
    <h4>Gemini</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prompt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prompt)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Gemini.Net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gemini.Net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gemini.Net.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gemini.Net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gemini" asp-action="Index">GeminiApi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gemini.Net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>